### ISSUE TITLE
Community restricted to lower case chars

### ISSUE THREAD

**Issue by crokkon** [jakipatryk/steeditor#72]
#### Expected behavior
The `community` field in the post's `json_metadata` is (from Steem-perspective) only required to be valid JSON, there is no restriction on characters or formats from the blockchain implementation: https://github.com/steemit/steem/blob/c6b865b6f27999cba38f3840151c8306f14f3371/libraries/protocol/steem_operations.cpp#L86

#### Actual behavior
Steeditor requires the `community` field to consist of lower case chars only and shows an error message when other chars are used.
While lower-case chars only is quite common for the community field across apps, not all apps do this. Actifit for example uses a list in the community field. The blockchain allows any content as long as the resulting `json_metadata` is valid JSON.

#### How to reproduce
Enter upper case or special chars in the `community` field
![screenshot_2018-08-25_12-59-51](https://user-images.githubusercontent.com/33018033/44617651-d0eb1d00-a866-11e8-986a-317fca586a6a.png)

Corresponding check in the code:
https://github.com/jakipatryk/steeditor/blob/6911916e38eb7a8919e6a336def474d8e10dbeb8/src/app/editor/components/community-partial-form/community-partial-form.component.spec.ts#L31

My TS skills are not sufficient to provide a PR which ensures only valid JSON.

#### Environment
Browser: Chrome 68.0
Steeditor.app at rev. 6911916

**Comment by crokkon** [comment]
Good point about the connection between communities and accounts for hivemind! In that context, the same validator as for accounts makes sense. However, the account naming rules are a bit more complex than `/^[a-z][a-z0-9.-]{2,}$/`, see here:
https://github.com/steemit/condenser/blob/374aa623c7b364b7e2a6ccbdf9194b5f8148069a/src/app/utils/ChainValidation.js#L6 (excl. the bad actor part)

**Comment by jakipatryk** [comment]
I wonder if it would be possible to create a single RegEx which would cover all these rules (I'm pretty bad at that). Otherwise, it would make sense to create a list of validators (ex. like [there](https://github.com/jakipatryk/steeditor/blob/master/src/app/editor/validators/tags.validators.ts)) for an account name.
