### ISSUE TITLE
Editor freezes when I try to open posts from a specific app

### ISSUE THREAD

**Issue by mcyusuf** [jakipatryk/steeditor#80]
### Expected behavior
When trying to edit a post from my blog using the steeditor app, there shouldn't be issues with some posts due to its json metadata.
### Actual behavior
If I try to open a post from __Actifit app__ specifically, the editor freezes and I can't use it till I restart the app afresh.
### How to reproduce
* Am not sure how to get a post with __metadata__ like the one broadcasted by __Actifit__, it has `"` enclosing the metadata.
```
"{"community":["actifit"],"step_count":["12000"],"activity_type":["Cycling, Daily Activity"],"tags":["mcyusuf","health","fitness","cycling","actifit"],"heightUnit":["cm"],"weightUnit":["kg"],"chestUnit":["cm"],"waistUnit":["cm"],"thighsUnit":["cm"],"image":["https://cdn.steemitimages.com/DQma3XriZxvHMWep4xjALkgQ1foWoQf24Ksq24FyrkRMcH3/A-4.I.png"],"appType":"","actiCrVal":"5310f62f01b497b52017269777384951ebe27ecbcaa3f9859c06af05626b9352c91d171d947260330a21b2acf2f85367","app":"actifit/v0.3.1"}"
```
* Open steeditor and locate the post.
* Click the edit icon and notice the bug.
### Recording of the Bug
https://youtu.be/uSiSM0E7rx8
### Working environment
* Android 8.1 Oreo
* Chrome version 66.0.3359.158

**Comment by jakipatryk** [comment]
Good catch. Although it is caused by (IMO) incorrectly set up community by the Actifit app, it shouldn't freeze the app.
