### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by omideleayo** [jakipatryk/steeditor#81]
Hi, 
I recently start writing for projects via utopian, may I provide some documentation like FAQ for this project. 
You may also  request other forms of documents needed for the project.

**Comment by jakipatryk** [comment]
Hey! I'm not sure how it would look like, could you elaborate a bit?

**Comment by omideleayo** [comment]
FAQs is a document which would help users navigate easily on the site. 
It answers basic questions users can have about the project.

**Comment by jakipatryk** [comment]
I don't think the FAQ for users is needed as it is a relatively simple app, but FAQ for developers (those who want to contribute, clone the project for their own idea) would be very welcome.

**Comment by omideleayo** [comment]
OK thanks, 
if you need FAQs for users later on or privacy policy, you can contact me
