### ISSUE TITLE
Tags should not allow special characters except for single -

### ISSUE THREAD

**Issue by mightypanda-x** [jakipatryk/steeditor#84]
#### Expected Behavior
Tags should prevent a user from entering all invalid special characters except one single - between two words.

#### Actual Behavior
Tags allow all special characters (!@$%^&*()) except for #. When trying to publish a post, steem throws a broadcast error without any details.

#### Steps to Reproduce
- Login to https://steeditor.app
- Select draft from the top menu and then proceed to select + in the bottom right corner to add a new draft.
- Turn off use template and click create.
- Enter any title and body text.
- Enter tags with special characters Ex. test/test
- Click on Next twice to go to summary section and click Send.
- Notice the broadcast error at the bottom of the page.

#### Proposed fix:
Use following regex for testing a valid tag: **/^[a-z0-9]+(-[a-z0-9]+)*$/**

#### Recording of the issue
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/13856451/45059646-8ed58e80-b051-11e8-8723-6164adb317e8.gif)

![image](https://user-images.githubusercontent.com/13856451/45059517-1ff83580-b051-11e8-999a-6d4d7706a7ae.png)

- **Browser**: Google Chrome ( 69.0.3497.81 Version)
- **Operating system**: OSX 10.11.6

**Comment by jakipatryk** [comment]
The broadcast error is most likely caused by the invalid first tag. As you said, it cannot contain special chars, because besides being the first tag, it is also set as a category. And the category is validated on the blockchain level. However, other tags aren't validated there.

Should we (at the Steeditor level) validate only the first tag or all of them?

**Comment by mightypanda-x** [comment]
I think it should be done for all tags so search by tags works right in all apps.
