### ISSUE TITLE
Invalid permlink character error

### ISSUE THREAD

**Issue by crokkon** [jakipatryk/steeditor#89]
#### Expected behavior
Steeditor builds a permlink from the post title. However, not all characters are allowed in permlinks. Steeditor should allow any characters in the title and replace invalid permlink characters to form a working permlink from the title.

#### Actual behavior
Underscore (`_`) chars from the title are not allowed in the permlink and are not replaced. The comment broadcast call to SteemConnect returns code 500 with `{"error":"server_error","error_description":"false: Invalid permlink character: _"}` and Steeditor shows an error:
![error](https://user-images.githubusercontent.com/33018033/46654504-4c035b00-cba9-11e8-93c5-cd7395b39d7e.png)

#### How to reproduce
Try to submit a post with underscores in the title, e.g.
![title](https://user-images.githubusercontent.com/33018033/46654593-879e2500-cba9-11e8-982e-6ac0d3cf322a.png)

NB: steemit replaces underscores with "-".

#### Environment
Chrome 69.0
Steeditor as live on https://steeditor.app on 18-10-09

**Comment by crokkon** [comment]
Related: https://github.com/pid/speakingurl/issues/103
`{ custom:{'_': '-'}` should do the trick, but I don't know how to insert this here:

https://github.com/jakipatryk/steeditor/blob/bb61694e403747957ae2a0db0369c2375239969b/src/core/steemize/withPermlink.ts#L12

**Comment by jakipatryk** [comment]
This should do the job: 
```typescript
export const createPermlink: (title: string) => string = ifElse(
  isEmpty,
  always(`${Date.now()}`),
  o(
    slug => `${slug}-${Date.now()}`,
    title => getSlug(title, { custom: { _: '-' } })
  )
);
```

**Comment by crokkon** [comment]
Cool! Not sure if your example is meant for me to do a PR - I don't have a dev environment ready to test it with this change, so I'd prefer if you could take care of it :)
