### ISSUE TITLE
"Remove Draft" button after sending a post is not functioning 

### ISSUE THREAD

**Issue by tony-duke** [jakipatryk/steeditor#97]
Normally,  after you are done creating a post and you send it to the steem blockchain,  you are given the option to **remove draft**, the button has not been clicking for over a week now .

**Comment by jakipatryk** [comment]
What browser/OS do you use?

**Comment by tony-duke** [comment]
It's now functioning properly, it just happens sometimes. I use an Android 7.1 and Chrome browser.
